print("Python is awesome".capitalize())
print("PYTHON IS KING".lower())
print("python is hot".upper())
print("Harry potter and the half-blood prince".title())
print("AVENGER:the war of infinity".swapcase())